[platformio]
default_envs = sticky-release

[env]
platform = espressif32@6.11.0
board = sticky_esp32s3
framework = espidf
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder
board_build.partitions = partitions.csv

build_flags =
    -DSTICKY_FIRMWARE_VERSION=\"0.1.2\"

[env:sticky-debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DSTICKY_BUILD_PROFILE=\"debug\"
    -DSTICKY_LOG_COMPILE_LEVEL=5
    -DSTICKY_LOG_BOOT_DETAILS_ENABLED=1
    -DSTICKY_LOG_POWER_DETAILS_ENABLED=1
    -DSTICKY_LOG_HEARTBEAT_ENABLED=1
    -DSTICKY_LOG_DISPLAY_TIMING_ENABLED=0
    -DSTICKY_LOG_TOUCH_SAMPLES_ENABLED=1
    -DSTICKY_LOG_TOUCH_DRIVER_OUTPUT_ENABLED=1
    -DSTICKY_LOG_MOTION_SAMPLES_ENABLED=0
    -DSTICKY_LOG_PET_ANIMATION_ENABLED=0
    -DSTICKY_LOG_STATUS_ANIMATION_ENABLED=0
    -DSTICKY_LOG_BOOK_ANIMATION_ENABLED=0
    -DSTICKY_LOG_RTC_READS_ENABLED=0
    -DSTICKY_LOG_DESKTOP_PET_ENABLED=1
    -DSTICKY_DESKTOP_PET_TEST_MODE=0
    -DSTICKY_ONBOARDING_TEST_MODE=1
    -DSTICKY_POWER_TEST_MODE=0
    -DSTICKY_LOG_TIMER_TICKS_ENABLED=0

[env:sticky-power-test]
build_type = debug
build_flags =
    ${env.build_flags}
    -DSTICKY_BUILD_PROFILE=\"power-test\"
    -DSTICKY_LOG_COMPILE_LEVEL=5
    -DSTICKY_LOG_BOOT_DETAILS_ENABLED=1
    -DSTICKY_LOG_POWER_DETAILS_ENABLED=1
    -DSTICKY_LOG_HEARTBEAT_ENABLED=1
    -DSTICKY_LOG_DISPLAY_TIMING_ENABLED=0
    -DSTICKY_LOG_TOUCH_SAMPLES_ENABLED=1
    -DSTICKY_LOG_TOUCH_DRIVER_OUTPUT_ENABLED=1
    -DSTICKY_LOG_MOTION_SAMPLES_ENABLED=0
    -DSTICKY_LOG_PET_ANIMATION_ENABLED=0
    -DSTICKY_LOG_STATUS_ANIMATION_ENABLED=0
    -DSTICKY_LOG_BOOK_ANIMATION_ENABLED=0
    -DSTICKY_LOG_RTC_READS_ENABLED=0
    -DSTICKY_LOG_DESKTOP_PET_ENABLED=1
    -DSTICKY_DESKTOP_PET_TEST_MODE=0
    -DSTICKY_ONBOARDING_TEST_MODE=1
    -DSTICKY_POWER_TEST_MODE=1
    -DSTICKY_LOG_TIMER_TICKS_ENABLED=0

[env:sticky-release]
build_type = release
build_flags =
    ${env.build_flags}
    -DSTICKY_BUILD_PROFILE=\"release\"
    -DSTICKY_LOG_COMPILE_LEVEL=3
    -DSTICKY_LOG_BOOT_DETAILS_ENABLED=0
    -DSTICKY_LOG_POWER_DETAILS_ENABLED=0
    -DSTICKY_LOG_HEARTBEAT_ENABLED=0
    -DSTICKY_LOG_DISPLAY_TIMING_ENABLED=0
    -DSTICKY_LOG_TOUCH_SAMPLES_ENABLED=1
    -DSTICKY_LOG_TOUCH_DRIVER_OUTPUT_ENABLED=1
    -DSTICKY_LOG_MOTION_SAMPLES_ENABLED=0
    -DSTICKY_LOG_PET_ANIMATION_ENABLED=0
    -DSTICKY_LOG_STATUS_ANIMATION_ENABLED=0
    -DSTICKY_LOG_BOOK_ANIMATION_ENABLED=0
    -DSTICKY_LOG_RTC_READS_ENABLED=0
    -DSTICKY_LOG_DESKTOP_PET_ENABLED=0
    -DSTICKY_DESKTOP_PET_TEST_MODE=0
    -DSTICKY_ONBOARDING_TEST_MODE=0
    -DSTICKY_POWER_TEST_MODE=0
    -DSTICKY_LOG_TIMER_TICKS_ENABLED=0
