#include "ui_language.h"

#include <atomic>
#include <cstring>

#include "font.h"

namespace {

struct Translation {
    const char *english;
    const char *chinese;
};

std::atomic<UiLanguage> s_language{UiLanguage::English};

// UI copy stays centralized so every app can switch language without owning
// another settings model. User-entered names and custom status text are never
// translated.
// 集中维护界面文案，所有APP共享语言设置；用户输入的名字和状态不会被翻译。
constexpr Translation kTranslations[] = {
    {"CHOOSE AN APP", "选择应用"},
    {"TAP A CARD  /  SWIPE DOWN TO CLOSE", "点击卡片 / 下滑关闭"},
        {"Home", "主页"},
        {"Settings", "设置"},
        {"Baby Week", "孕周"},
        {"SETTINGS", "设置"},
        {"DEVICE AND FRAMEWORK CONTROLS", "设备与框架控制"},
        {"LANGUAGE: ENGLISH", "语言：英文"},
        {"SET DEVICE TIME", "设置设备时间"},
        {"DISPLAY CLEAN REFRESH", "屏幕清洁全刷"},
        {"RETURN HOME", "返回主页"},
        {"YYYY / MM / DD / HH / MM", "年 / 月 / 日 / 时 / 分"},
        {"ENTER 12 DIGITS, THEN SAVE", "输入12位数字后保存"},
        {"INVALID DATE OR RTC WRITE FAILED", "日期无效或时钟写入失败"},
        {"BACK", "返回"},
        {"SAVE", "保存"},
    {"STICKY CORE", "STICKY 核心"},
    {"FRAMEWORK", "通用框架"},
    {"RTC  READY", "时钟  正常"},
    {"RTC  UNAVAILABLE", "时钟  不可用"},
    {"SWIPE UP FOR APPS", "向上滑动打开应用"},
    {"Pet", "桌宠"},
    {"Pomodoro", "番茄"},
    {"Time", "专注"},
    {"Status", "状态"},
    {"Board", "看板"},
    {"Answers of", "答案"},
    {"book", "之书"},
    {"Baby", "孕周"},
    {"Week", "看板"},
    {"App", "应用"},
    {"BACK", "返回"},
    {"NEXT", "下一步"},
    {"START", "开始"},
    {"END", "结束"},
    {"CANCEL", "取消"},
    {"DELETE", "删除"},
    {"DEL", "删除"},
    {"CLEAR", "清空"},
    {"EDIT", "修改"},
    {"APPLY", "应用"},
    {"PAUSE", "暂停"},
    {"PAUSED", "已暂停"},
    {"RESUME", "继续"},
    {"SELECTED", "已选择"},
    {"CUSTOM", "自定义"},
    {"CUSTOM TIME", "自定义时间"},
    {"USE THIS TIME", "使用此时间"},
    {"END SESSION", "结束专注"},
    {"END SESSION?", "结束专注？"},
    {"ARE YOU SURE?", "确定要结束吗？"},
    {"TIME LEFT", "剩余时间"},
    {"ALARM SOUNDING", "时间到了"},
    {"STICKY POMODORO TIMER", "STICKY 番茄专注"},
    {"MIN", "分钟"},
    {"HR", "小时"},
    {"SEC", "秒"},
    {"SET DEVICE TIME", "设置设备时间"},
    {"YEAR / MONTH / DAY / HOUR / MINUTE", "年 / 月 / 日 / 时 / 分"},
    {"SET DUE DATE", "设置预产期"},
    {"USE YOUR CONFIRMED ESTIMATED DUE DATE", "请输入确认后的预产期"},
    {"CHECK THE DATE AND TRY AGAIN", "日期有误，请重新输入"},
    {"TAP A NUMBER TO REPLACE THE VALUE", "点击数字即可替换当前值"},
    {"SAVED ONLY ON THIS DEVICE", "数据仅保存在本设备"},
    {"CURRENT DEVELOPMENT STAGE", "当前发育阶段"},
    {"40-WEEK DEVELOPMENT PROGRESS", "40 周孕期进度"},
    {"FIRST TRIMESTER", "孕早期"},
    {"SECOND TRIMESTER", "孕中期"},
    {"THIRD TRIMESTER", "孕晚期"},
    {"STICKY STATUS BOARD", "STICKY 状态看板"},
    {"SELECT ONE TO DISPLAY", "选择一个状态进行展示"},
    {"BUSY", "忙碌中"},
    {"MEETING", "会议中"},
    {"ON CALL", "通话中"},
    {"OPEN TO TALK", "欢迎交流"},
    {"OPEN TO", "欢迎"},
    {"TALK", "交流"},
    {"REST", "休息中"},
    {"TYPE STATUS_", "输入状态_"},
    {"TYPE AT LEAST 1 CHARACTER", "请至少输入一个字符"},
    {"NUMBER KEYS", "数字键盘"},
    {"SPACE", "空格"},
    {"ABC", "字母"},
    {"BOOK OF ANSWERS", "答案之书"},
    {"ANSWER TYPE", "答案类型"},
    {"MESSAGE", "一句话"},
    {"YES OR NO", "是或否"},
    {"ASK AGAIN", "再问一次"},
    {"SHAKE FOR 3 SECONDS", "持续摇晃 3 秒"},
    {"KEEP YOUR QUESTION IN MIND", "请在心中默念问题"},
    {"HOLD STILL", "请保持静止"},
    {"LET THE CRYSTAL SETTLE", "让水晶球安静下来"},
    {"THE CRYSTAL IS MOVING", "水晶球正在转动"},
    {"SHAKING...", "摇晃中……"},
    {"THINKING...", "思考中……"},
    {"THE CRYSTAL", "水晶球"},
    {"HAS DECIDED", "已有答案"},
    {"YOUR ANSWER IS READY", "你的答案已准备好"},
    {"REVEALING...", "揭晓中……"},
    {"THE CRYSTAL HAS DECIDED", "水晶球已经决定"},
    {"YES", "是"},
    {"NO", "否"},
    {"UNCLEAR", "尚不明确"},
    {"HELLO, I'M STICKY!", "你好，我是 STICKY！"},
    {"LET'S GROW TOGETHER!", "让我们一起成长！"},
    {"I'LL SHOW YOU", "接下来由我介绍"},
    {"HOW TO USE STICKY.", "怎样使用 STICKY。"},
    {"CARE FOR YOUR PET", "照顾你的桌宠"},
    {"KNOW WHAT EACH VALUE", "了解每个数值"},
    {"MEANS", "代表什么"},
    {"GROWTH", "成长"},
    {"UNLOCKS NEW LIFE STAGES", "解锁新的成长阶段"},
    {"LOVE", "亲密"},
    {"DEEPENS YOUR BOND", "加深彼此的感情"},
    {"FULLNESS", "饱腹"},
    {"SHOWS WHEN TO FEED", "提示何时需要喂食"},
    {"ENERGY", "精力"},
    {"REQUIRED FOR INTERACTIONS", "互动需要消耗精力"},
    {"YOUR CARE SHAPES ITS GROWTH", "你的照顾决定它的成长"},
    {"DAILY CHOICES BUILD ITS PERSONALITY", "每天的选择塑造它的性格"},
    {"FEED OFTEN", "经常喂食"},
    {"PET OFTEN", "经常抚摸"},
    {"PLAY OFTEN", "经常玩耍"},
    {"FOODIE", "美食家"},
    {"AFFECTIONATE", "亲密型"},
    {"ACTIVE", "活力型"},
    {"FIVE WAYS TO USE STICKY", "STICKY 的五种玩法"},
    {"YOUR LITTLE ONE IS HERE", "你的小伙伴就在这里"},
    {"Pomodoro Time", "番茄专注"},
    {"IT'S TIME TO FOCUS", "现在开始专注"},
    {"Status Board", "状态看板"},
    {"SHOW YOUR STATUS", "展示你的当前状态"},
    {"Answers of book", "答案之书"},
    {"ASK WITHIN, THE BOOK ANSWERS", "在心中提问，让书来回答"},
    {"FIND YOUR APPS", "找到你的应用"},
    {"OPEN, CLOSE, RETURN HOME, OR SLEEP", "打开、关闭、回到主页或休眠"},
    {"SWIPE DOWN", "向下滑动"},
    {"TO CLOSE", "关闭启动器"},
    {"AI KEY", "AI 按键"},
    {"TAP: OPEN", "单击：打开"},
    {"DOUBLE TAP: PET", "双击：回到桌宠"},
    {"HOLD BOTH", "同时按住"},
    {"SIDE KEYS", "两个侧键"},
    {"TO SLEEP", "进入休眠"},
    {"TAP AN APP", "点击应用"},
    {"TO LAUNCH", "即可启动"},
    {"SWIPE UP", "向上滑动"},
    {"TO OPEN", "打开启动器"},
    {"TURN TO CHOOSE", "旋转设备来选择"},
    {"OPEN THE LAUNCHER, THEN MOVE STICKY", "先打开启动器，再转动 STICKY"},
    {"LANDSCAPE -> PORTRAIT", "横屏 → 竖屏"},
    {"OPENS POMODORO TIME", "打开番茄专注"},
    {"PORTRAIT -> LANDSCAPE", "竖屏 → 横屏"},
    {"OPENS STATUS BOARD", "打开状态看板"},
    {"SHAKE STICKY", "摇晃 STICKY"},
    {"OPENS ANSWERS OF BOOK", "打开答案之书"},
    {"SKIP TUTORIAL", "跳过教程"},
    {"FEED", "喂食"},
    {"PLAY", "玩耍"},
    {"CALL HER HOME", "叫它回家"},
    {"MANUAL", "说明"},
    {"TEST", "测试"},
    {"EGG", "宠物蛋"},
    {"HATCHLING", "幼兔"},
    {"CHILD", "童年期"},
    {"YOUTH", "青年期"},
    {"ADULT", "成年期"},
    {"ELDER", "陪伴期"},
    {"NEUTRAL", "平静"},
    {"CONTENT", "满足"},
    {"HAPPY", "开心"},
    {"ECSTATIC", "兴奋"},
    {"HUNGRY", "饥饿"},
    {"TIRED", "疲惫"},
    {"SAD", "难过"},
    {"UPSET", "不开心"},
    {"MISERABLE", "很低落"},
    {"SLEEPING PEACEFULLY", "正在安心睡觉"},
    {"WAKE UP", "叫醒它"},
    {"RESTORES 6% ENERGY PER MINUTE", "每分钟恢复 6% 精力"},
    {"PRESS WAKE UP TO END REST", "点击叫醒结束休息"},
    {"NAME YOUR FRIEND", "给伙伴起个名字"},
    {"CHOOSE A NEW NAME", "选择一个新名字"},
    {"A NAME MAKES IT YOURS", "名字让它成为独特伙伴"},
    {"SAVE NAME", "保存名字"},
    {"LETTERS  NUMBERS  ONE SPACE", "支持字母、数字和一个空格"},
    {"BACK KEEPS THE CURRENT NAME", "返回将保留当前名字"},
    {"THIS FRIEND IS WAITING FOR A NAME", "这个伙伴正在等待一个名字"},
    {"TAP THE EGG GENTLY", "轻轻点击宠物蛋"},
    {"THREE TAPS TO WELCOME IT", "点击三次迎接它"},
    {"A TINY CRACK APPEARED!", "蛋壳出现了一条小裂缝！"},
    {"IT CAN HEAR YOU NOW", "它现在能听到你了"},
    {"TWO LITTLE EARS!", "露出了两只小耳朵！"},
    {"ONE MORE GENTLE TAP", "再轻轻点击一次"},
    {"HELLO, LITTLE ONE!", "你好，小家伙！"},
    {"YOUR FIRST DAY STARTS NOW", "相伴的第一天开始了"},
    {"A NEW FRIEND IS HERE", "一位新朋友来到这里"},
    {"SOMETHING WARM IS WAITING INSIDE", "一个温暖的小生命正在等待"},
    {"BE GENTLE. A FRIEND IS GROWING.", "轻一点，新朋友正在成长。"},
    {"NEXT STAGE IS READY!", "已经可以进入下一阶段！"},
    {"CARE FOR ME TO HELP ME GROW.", "照顾我，陪我慢慢成长。"},
    {"CARE FOR ME TO HELP ME GROW UP.", "继续照顾我，陪我长大。"},
    {"CARE FOR ME TO FIND MY PATH.", "继续照顾我，帮助我找到方向。"},
    {"A LITTLE CELEBRATION", "小小的纪念日"},
    {"DAYS TOGETHER", "相伴天数"},
    {"EVERY DAY TOGETHER MATTERS.", "相伴的每一天都很珍贵。"},
    {"THANK YOU FOR CARING FOR ME!", "谢谢你一直照顾我！"},
    {"A NEW DAY TOGETHER!", "一起迎接新的一天！"},
    {"GOOD MORNING! I'M GLAD YOU'RE HERE.", "早上好！很开心你在这里。"},
    {"GOOD MORNING! I FEEL RESTED.", "早上好！我休息得很好。"},
    {"GOOD NIGHT. STAY CLOSE.", "晚安，陪在我身边吧。"},
    {"I'M GETTING SLEEPY...", "我开始困了……"},
    {"I'M LOW ON ENERGY. MAY I REST?", "我的精力不多了，可以休息吗？"},
    {"YUM YUM!", "好好吃！"},
    {"THAT FEELS SO NICE!", "这样摸摸真舒服！"},
    {"ONE MORE LITTLE HOP!", "再跳一下！"},
    {"FRESH AND FLUFFY!", "干净又蓬松！"},
    {"I'M READY TO GROW!", "我准备好长大了！"},
    {"LOOK! I GREW!", "看，我长大了！"},
    {"CARROT. NOW. PLEASE.", "现在想吃胡萝卜！"},
    {"MY STOMACH HAS OPINIONS.", "我的肚子在提意见。"},
    {"EMPTY RABBIT, SAD RABBIT.", "肚子空空，兔兔难过。"},
    {"COULD USE A HEAD PAT.", "想要摸摸头。"},
    {"NEED... BURROW...", "想要……钻进被窝……"},
    {"JUST FIVE MORE MINUTES.", "再睡五分钟。"},
    {"I'M LISTENING.", "我在听。"},
    {"TELL ME ABOUT YOUR DAY.", "和我说说今天吧。"},
    {"YOU'RE MY FAVORITE PERSON.", "你是我最喜欢的人。"},
    {"HOME IS WHERE YOU ARE.", "有你的地方就是家。"},
    {"EXPLORE STICKY APPS", "探索 STICKY 应用"},
    {"TIME'S UP", "专注时间到"},
    {"THINK OF A QUESTION", "在心中想好一个问题"},
    {"TO RECEIVE YOUR ANSWER", "来获取你的答案"},
    {"SHAKE GENTLY FOR 3 SEC", "轻轻摇晃 3 秒"},
    {"YES / NO", "是 / 否"},
    {"WHAT DO YOU WANT?", "你想问什么？"},
    {"WELCOME, LITTLE ONE!", "欢迎你，小家伙！"},
    {"OUR DAYS TOGETHER BEGIN NOW", "我们的陪伴从今天开始"},
    {"HATCHLING  GROWTH 10  LOVE 18", "幼兔  成长 10  亲密 18"},
    {"TWITCHING MY NOSE.", "鼻子轻轻动了一下。"},
    {"JUST VIBING.", "正在悠闲地放空。"},
    {"DID SOMEBODY SAY CARROT?", "刚才是谁说了胡萝卜？"},
    {"I'M 90% EARS.", "我大概九成都是耳朵。"},
    {"PLOTTING SOMETHING. PROBABLY.", "好像在计划什么。"},
    {"THE GARDEN WAS A MISTAKE.", "花园里的冒险有点失策。"},
    {"HOPPING IS CONTROLLED FALLING.", "跳跃就是有技巧地落下。"},
    {"LOOKING CUTE ON PURPOSE.", "是故意这么可爱的。"},
    {"I'M A REGISTERED HOPSTER.", "我可是认证跳跃选手。"},
    {"HOP HOP HOP.", "跳呀，跳呀，跳呀。"},
    {"GOING SOMEWHERE IMPORTANT.", "正要去一个重要的地方。"},
    {"PRETENDING I HAVE A DESTINATION.", "假装自己有个目的地。"},
    {"WABBIT ON THE MOVE!", "兔兔出发啦！"},
    {"RUN FAST. THINK LATER.", "先快跑，等会再想。"},
    {"RECONNAISSANCE MISSION.", "正在执行侦察任务。"},
    {"ZZZ... CARROTS... ZZZ...", "呼呼……胡萝卜……"},
    {"*TWITCHES EAR IN DREAM*", "梦里的耳朵动了一下"},
    {"DREAMING OF AN OPEN FRIDGE.", "梦见了打开的冰箱。"},
    {"I SLEEP WITH ONE EYE OPEN.", "我睡觉时也会偷偷留意。"},
    {"I REQUIRE PRODUCE.", "我现在需要一些蔬菜。"},
    {"I MISS THE GARDEN.", "我有点想念花园了。"},
    {"EARS ARE HEAVY TODAY.", "今天的耳朵有点沉。"},
    {"HOPPING IS EXHAUSTING.", "跳来跳去好累呀。"},
    {"I'M STILL GETTING TO KNOW YOU.", "我还在慢慢了解你。"},
    {"YOU CAN SIT A LITTLE CLOSER.", "你可以坐得再近一点。"},
    {"MY EARS HEAR EVERYTHING.", "我的耳朵什么都听得见。"},
    {"DID YOU BRING A CARROT?", "你带胡萝卜来了吗？"},
    {"LET'S TAKE IT SLOW.", "我们慢慢来吧。"},
    {"I'M GLAD YOU CAME BACK.", "很高兴你回来了。"},
    {"SHALL WE HOP SOMEWHERE?", "我们去别处跳跳吧？"},
    {"YOU MAKE THIS ROOM FEEL WARM.", "你让这个房间很温暖。"},
    {"I SAVED THIS SPOT FOR YOU.", "我为你留了这个位置。"},
    {"LET'S SPEND MORE TIME TOGETHER.", "我们再多待一会吧。"},
    {"I TRUST YOU WITH MY CARROTS.", "我愿意把胡萝卜交给你。"},
    {"EVERY DAY IS BETTER WITH YOU.", "有你在，每天都更好。"},
    {"I KNEW YOU WOULD COME BACK.", "我就知道你会回来。"},
    {"LET'S STAY TOGETHER A WHILE.", "我们再陪彼此一会吧。"},
    {"I'M READY FOR AN ADVENTURE.", "我已经准备好去冒险了。"},
    {"MY LEGS FEEL SO SPRINGY!", "我的腿充满了弹性！"},
    {"I CAN REACH HIGHER NOW.", "我现在能够得更高了。"},
    {"WHERE SHOULD WE EXPLORE?", "我们去哪里探索呢？"},
    {"ENERGY FOR ADVENTURES!", "冒险需要充足精力！"},
    {"MY FUR GREW EXTRA SOFT!", "我的毛又变柔软了！"},
    {"CATCH ME IF YOU CAN!", "来追我呀！"},
    {"I'M LEARNING NEW THINGS.", "我正在学新东西。"},
    {"WILL YOU SHOW ME AROUND?", "你愿意带我四处看看吗？"},
    {"MY LEGS ARE STILL WOBBLY.", "我的腿还有点摇晃。"},
    {"LET'S GO SOMEWHERE TOGETHER.", "我们一起出发吧。"},
    {"I SAVED MY BEST HOP FOR YOU.", "我把最棒的一跳留给你。"},
    {"YOU MAKE ME FEEL BRAVE.", "你让我变得勇敢。"},
    {"WE'RE THE BEST ADVENTURE TEAM.", "我们是最棒的冒险搭档。"},
    {"I'LL ALWAYS HOP BACK TO YOU.", "我总会跳回你身边。"},
    {"YOU HELPED ME GROW THIS STRONG.", "是你陪我长得这么健壮。"},
    {"OUR JOURNEY SHAPED ME...", "我们的旅程塑造了我……"},
    {"MY PERSONALITY IS BLOOMING...", "我的性格正在绽放……"},
    {"SOMETHING IS HAPPENING...", "好像有变化在发生……"},
    {"GROWING INTO MYSELF...", "正在长成自己的模样……"},
    {"FINDING MY PATH...", "正在寻找自己的方向……"},
    {"GROWING...", "正在成长……"},
    {"I'M ALL GROWN UP!", "我已经长大了！"},
    {"I FOUND MY PATH!", "我找到自己的方向了！"},
    {"EVERY MOMENT HELPED ME GROW.", "每一个瞬间都陪我成长。"},
    {"ALL OUR DAYS SHAPED WHO I AM.", "共度的日子塑造了现在的我。"},
    {"A WARM LIGHT SURROUNDS ME.", "一道温暖的光包围着我。"},
    {"ONE LAST BRIGHT MOMENT...", "最后一个闪亮瞬间……"},
    {"ONE MORE MOMENT...", "再等一个瞬间……"},
    {"MY EARS ARE GETTING LONGER!", "我的耳朵变长了！"},
    {"OUR ADULT JOURNEY BEGINS!", "我们的成年旅程开始了！"},
    {"THE FOODIE IN ME GREW STRONG!", "我成了真正的美食家！"},
    {"MY HEART GREW WITH OUR BOND!", "我的心随着羁绊一起成长！"},
    {"I'M READY FOR BIG ADVENTURES!", "我准备好迎接大冒险了！"},
    {"MY YOUTH PATH BEGINS!", "我的青年之路开始了！"},
    {"MY FOODIE PATH BEGINS!", "我的美食之路开始了！"},
    {"MY HEART PATH BEGINS!", "我的亲密之路开始了！"},
    {"MY ACTIVE PATH BEGINS!", "我的活力之路开始了！"},
    {"LOOK HOW FAR WE'VE COME!", "看看我们一起走了多远！"},
    {"CHOOSE OUR NEXT", "选择我们的下一次"},
    {"ADVENTURE", "冒险"},
    {"ONE LAST MOMENT TOGETHER", "最后再共度一个瞬间"},
    {"SHARE A SNACK", "分享点心"},
    {"FOODIE PATH", "美食之路"},
    {"STAY CLOSE", "彼此陪伴"},
    {"AFFECTIONATE PATH", "亲密之路"},
    {"RACE OUTSIDE", "户外赛跑"},
    {"ACTIVE PATH", "活力之路"},
    {"THIS CHOICE SHAPES THE YOUTH STAGE", "这个选择会塑造青年阶段"},
    {"TAP THE MOMENT THAT FEELS LIKE US", "点击最像我们的那个瞬间"},
    {"IN YOUR HEART", "在你心中"},
    {"UNKNOWN", "未知"},
    {"FOODIE YOUTH", "美食青年期"},
    {"HEART YOUTH", "亲密青年期"},
    {"ACTIVE YOUTH", "活力青年期"},
    {"FOODIE ADULT", "美食成年期"},
    {"HEART ADULT", "亲密成年期"},
    {"ACTIVE ADULT", "活力成年期"},
    {"PET TEST PANEL", "桌宠测试面板"},
    {"CLOSE THIS PANEL", "关闭此面板"},
    {"THEN TAP THE EGG GENTLY", "然后轻轻点击宠物蛋"},
    {"EACH TAP IS SAVED", "每次点击都会保存"},
    {"NEXT DAY", "下一天"},
    {"SLEEP NOW", "立即睡觉"},
    {"GO OUT", "出门"},
    {"CONFIRM RESET", "确认重置"},
    {"RESET PET", "重置桌宠"},
    {"TAP RESET AGAIN TO CONFIRM", "再点一次重置以确认"},
    {"TEST CHANGES SAVE TO THE PET RECORD", "测试修改会保存到桌宠记录"},
    {"YOUR PET_", "你的桌宠_"},
};

}  // namespace

UiLanguage ui_language_get()
{
    return s_language.load(std::memory_order_acquire);
}

void ui_language_set(UiLanguage language)
{
    s_language.store(language, std::memory_order_release);
}

bool ui_language_is_chinese()
{
    return ui_language_get() == UiLanguage::ChineseSimplified;
}

const char *ui_text(const char *english)
{
    if (english == nullptr || !ui_language_is_chinese()) {
        return english;
    }
    for (const Translation &entry : kTranslations) {
        if (std::strcmp(entry.english, english) == 0) {
            return entry.chinese;
        }
    }
    return english;
}

int ui_text_width(const char *english, uint8_t scale)
{
    return font_text_width(ui_text(english), scale);
}
