#!/usr/bin/env python3
"""Generate the firmware's finite high-resolution e-paper Chinese glyph table."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def chinese_characters(source_root: Path) -> list[str]:
    result: set[str] = set()
    for pattern in ("*.cpp", "*.h"):
        for path in source_root.rglob(pattern):
            text = path.read_text(encoding="utf-8")
            for literal in re.findall(r'"(?:\\.|[^"\\])*"', text):
                result.update(char for char in literal if ord(char) > 0x7F)
    return sorted(result, key=ord)


def rasterize(
    font: ImageFont.FreeTypeFont, character: str, threshold: int
) -> list[int]:
    crop = Image.new("L", (24, 24), 0)
    draw = ImageDraw.Draw(crop)
    reference_bbox = draw.textbbox((0, 0), "国", font=font)
    draw.text((0, -reference_bbox[1]), character, font=font, fill=255)
    rows: list[int] = []
    for y_pos in range(24):
        bits = 0
        for x_pos in range(24):
            # Preserve enough edge detail for later size-aware resampling. The
            # 24px source retains regular strokes without coarse enlargement.
            if crop.getpixel((x_pos, y_pos)) >= threshold:
                bits |= 1 << x_pos
        rows.append(bits)
    return rows


def generate(
    font_path: Path, source_root: Path, output: Path, threshold: int
) -> None:
    characters = chinese_characters(source_root)
    font = ImageFont.truetype(str(font_path), 24)
    lines = [
        '// Generated by tools/generate_chinese_font_assets.py. Do not edit.',
        '#include "chinese_font_assets.h"',
        '',
        '#include <algorithm>',
        '#include <iterator>',
        '',
        'namespace {',
        '',
        'constexpr ChineseFontGlyph kGlyphs[] = {',
    ]
    for character in characters:
        rows = rasterize(font, character, threshold)
        values = ", ".join(f"0x{row:06X}U" for row in rows)
        lines.append(
            f"    {{0x{ord(character):04X}U, {{{values}}}}},  // {character}"
        )
    lines.extend(
        [
            '};',
            '',
            '}  // namespace',
            '',
            'const ChineseFontGlyph *chinese_font_glyph(uint32_t codepoint)',
            '{',
            '    const auto found = std::lower_bound(',
            '        std::begin(kGlyphs), std::end(kGlyphs), codepoint,',
            '        [](const ChineseFontGlyph &glyph, uint32_t value) {',
            '            return glyph.codepoint < value;',
            '        });',
            '    return found != std::end(kGlyphs) && found->codepoint == codepoint',
            '               ? found',
            '               : nullptr;',
            '}',
            '',
            'size_t chinese_font_glyph_count()',
            '{',
            '    return std::size(kGlyphs);',
            '}',
            '',
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(characters)} glyphs at {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--source-root", type=Path, default=Path("src"))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/ui/assets/chinese_font_assets.cpp"),
    )
    parser.add_argument(
        "--threshold",
        type=int,
        default=128,
        help="source grayscale threshold from 0 to 255",
    )
    args = parser.parse_args()
    if not 0 <= args.threshold <= 255:
        parser.error("--threshold must be between 0 and 255")
    generate(args.font, args.source_root, args.output, args.threshold)


if __name__ == "__main__":
    main()
