idf_component_register(
    SRCS
        "main.cpp"
        "board/board_power.cpp"
        "board/board_shared_spi.cpp"
        "core/app_log.cpp"
        "display/display_test_pattern.cpp"
        "display/sticky_display.cpp"
        "display/touch_test_pattern.cpp"
        "input/sticky_touch.cpp"
        "ui/canvas.cpp"
        "ui/font.cpp"
    INCLUDE_DIRS
        "."
        "board"
        "core"
        "display"
        "input"
        "ui"
    REQUIRES
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_spi
        esp_hw_support
        gt911
        seeed_epaper
        spi_flash
)

target_compile_features(${COMPONENT_LIB} PRIVATE cxx_std_17)
